# 内嵌数据库 h2
#spring:
#  datasource:
#    jdbc-url: jdbc:h2:file:~/.h2/h2
#    username:
#    password:
#    driver-class-name: org.h2.Driver
#  batch:
#    job:
#      enabled: false

# mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study?characterEncoding=utf-8&rewriteBatchedStatements=true
    username: root
    password: develop
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5  # 空闲连接数量
      maximum-pool-size: 20  # 最大连接数
      max-lifetime: 1800000  # 连接最大存活时间 30分钟
      idle-timeout: 300000  # 空闲连接超时时间 5分钟
      leak-detection-threshold: 30000  # 检测连接泄漏的时间阈值 30秒